// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAprXhtOIFXTVfCsi83-uDWOaFcSPHcGJk',
    appId: '1:594883657251:web:b73035397fec159fa2bb96',
    messagingSenderId: '594883657251',
    projectId: 'interview-app-7f65d',
    authDomain: 'interview-app-7f65d.firebaseapp.com',
    storageBucket: 'interview-app-7f65d.firebasestorage.app',
    measurementId: 'G-FCRQCE1QCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAusu4uHqWzanSm6lD5s3XKZN0strahPUM',
    appId: '1:594883657251:android:65e75c1213065db0a2bb96',
    messagingSenderId: '594883657251',
    projectId: 'interview-app-7f65d',
    storageBucket: 'interview-app-7f65d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi444Ol7AS8GMlM9jj8xOVzijg805VY_A',
    appId: '1:594883657251:ios:898e0929b6584695a2bb96',
    messagingSenderId: '594883657251',
    projectId: 'interview-app-7f65d',
    storageBucket: 'interview-app-7f65d.firebasestorage.app',
    iosBundleId: 'com.example.interviewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi444Ol7AS8GMlM9jj8xOVzijg805VY_A',
    appId: '1:594883657251:ios:898e0929b6584695a2bb96',
    messagingSenderId: '594883657251',
    projectId: 'interview-app-7f65d',
    storageBucket: 'interview-app-7f65d.firebasestorage.app',
    iosBundleId: 'com.example.interviewApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAprXhtOIFXTVfCsi83-uDWOaFcSPHcGJk',
    appId: '1:594883657251:web:adecf6bf6865d910a2bb96',
    messagingSenderId: '594883657251',
    projectId: 'interview-app-7f65d',
    authDomain: 'interview-app-7f65d.firebaseapp.com',
    storageBucket: 'interview-app-7f65d.firebasestorage.app',
    measurementId: 'G-JHE3VLHKPC',
  );
}
